export const TEXT = {
  modalTitle: 'Subscription Cancellation',
  cancelledTitle: 'Subscription Cancelled',
  offerTitle: 'We built this to help you land the job, this makes it a little easier.',
  offerBody: "We’ve been there and we’re here to help you.",
  getOffCTA: 'Get 50% off',
  noThanks: 'No thanks',
  acceptedH1: 'Great choice, mate!',
  acceptedBody: "You’re still on the path to your dream role. Let’s make it happen together!",
  acceptedCTA: 'Land your dream role',
  usageH1: 'Help us understand how you were using Migrate Mate.',
  usageCoach: "Mind letting us know why you’re cancelling? It helps us understand your experience and improve the platform.*",
  usageOfferInline: (priceNow: string, was: number) => `Get 50% off | $${priceNow} ${was}`,
  reasonsH1: "What’s the main reason for cancelling?",
  reasonsSub: 'Please take a minute to let us know why:',
  reasonsNeedSelect: 'To help us understand your experience, please select a reason for cancelling*',
  reasonTooExp: 'Too expensive',
  reasonPlatform: 'Platform not helpful',
  reasonNotRelevant: 'Not enough relevant jobs',
  reasonDecided: 'Decided not to move',
  reasonOther: 'Other',
  min25: 'Min 25 characters',
  please25: 'Please enter at least 25 characters so we can understand your feedback*',
  completeCancel: 'Complete cancellation',
  finishH1: 'Sorry to see you go, mate.',
  finishBody1: "Thanks for being with us, and you’re always welcome back.",
  finishBody2: "Your subscription is set to end on XX date. You’ll still have full access until then. No further charges after that.",
  finishFoot: 'Changed your mind? You can reactivate anytime before your end date.',
  backToJobs: 'Back to Jobs',
};
